/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultoresRouteImport } from './routes/_authenticated/consultores'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as ApiPublicN8nLeadRouteImport } from './routes/api/public/n8n-lead'
import { Route as ApiPublicWebhookFacebookRouteImport } from './routes/api/public/webhook/facebook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultoresRoute =
  AuthenticatedConsultoresRouteImport.update({
    id: '/consultores',
    path: '/consultores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicN8nLeadRoute = ApiPublicN8nLeadRouteImport.update({
  id: '/api/public/n8n-lead',
  path: '/api/public/n8n-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookFacebookRoute =
  ApiPublicWebhookFacebookRouteImport.update({
    id: '/api/public/webhook/facebook',
    path: '/api/public/webhook/facebook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultores': typeof AuthenticatedConsultoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/n8n-lead': typeof ApiPublicN8nLeadRoute
  '/api/public/webhook/facebook': typeof ApiPublicWebhookFacebookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultores': typeof AuthenticatedConsultoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/n8n-lead': typeof ApiPublicN8nLeadRoute
  '/api/public/webhook/facebook': typeof ApiPublicWebhookFacebookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consultores': typeof AuthenticatedConsultoresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/n8n-lead': typeof ApiPublicN8nLeadRoute
  '/api/public/webhook/facebook': typeof ApiPublicWebhookFacebookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assistente'
    | '/configuracoes'
    | '/consultores'
    | '/dashboard'
    | '/funil'
    | '/leads'
    | '/api/chat'
    | '/api/public/n8n-lead'
    | '/api/public/webhook/facebook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/assistente'
    | '/configuracoes'
    | '/consultores'
    | '/dashboard'
    | '/funil'
    | '/leads'
    | '/api/chat'
    | '/api/public/n8n-lead'
    | '/api/public/webhook/facebook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/assistente'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consultores'
    | '/_authenticated/dashboard'
    | '/_authenticated/funil'
    | '/_authenticated/leads'
    | '/api/chat'
    | '/api/public/n8n-lead'
    | '/api/public/webhook/facebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicN8nLeadRoute: typeof ApiPublicN8nLeadRoute
  ApiPublicWebhookFacebookRoute: typeof ApiPublicWebhookFacebookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultores': {
      id: '/_authenticated/consultores'
      path: '/consultores'
      fullPath: '/consultores'
      preLoaderRoute: typeof AuthenticatedConsultoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/n8n-lead': {
      id: '/api/public/n8n-lead'
      path: '/api/public/n8n-lead'
      fullPath: '/api/public/n8n-lead'
      preLoaderRoute: typeof ApiPublicN8nLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/facebook': {
      id: '/api/public/webhook/facebook'
      path: '/api/public/webhook/facebook'
      fullPath: '/api/public/webhook/facebook'
      preLoaderRoute: typeof ApiPublicWebhookFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsultoresRoute: typeof AuthenticatedConsultoresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsultoresRoute: AuthenticatedConsultoresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicN8nLeadRoute: ApiPublicN8nLeadRoute,
  ApiPublicWebhookFacebookRoute: ApiPublicWebhookFacebookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
